
package fr.biking.client.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBikingService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBikingService {


    /**
     * 
     * @param endPoint
     * @param startPoint
     * @return
     *     returns fr.biking.client.service.ArrayOfNavigationStep
     */
    @WebMethod(operationName = "CalculatePath", action = "http://tempuri.org/IBikingService/CalculatePath")
    @WebResult(name = "CalculatePathResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalculatePath", targetNamespace = "http://tempuri.org/", className = "fr.biking.client.service.CalculatePath")
    @ResponseWrapper(localName = "CalculatePathResponse", targetNamespace = "http://tempuri.org/", className = "fr.biking.client.service.CalculatePathResponse")
    public ArrayOfNavigationStep calculatePath(
        @WebParam(name = "startPoint", targetNamespace = "http://tempuri.org/")
        String startPoint,
        @WebParam(name = "endPoint", targetNamespace = "http://tempuri.org/")
        String endPoint);

}
